// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFE6A_ud9h_HYjWJHUoIGvd3UV1vRG7RE',
    appId: '1:1066839315758:web:ea2ce91a4d03d46c1a96bf',
    messagingSenderId: '1066839315758',
    projectId: 'reelstream1644',
    authDomain: 'reelstream1644.firebaseapp.com',
    storageBucket: 'reelstream1644.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_LQ5GhBOfuwomC7jCJ3V2Skar7lZWBnw',
    appId: '1:1066839315758:android:10a82ef3cdd930461a96bf',
    messagingSenderId: '1066839315758',
    projectId: 'reelstream1644',
    storageBucket: 'reelstream1644.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACgngk1fskzjnkwHomt7BwpVsaATeZvTQ',
    appId: '1:1066839315758:ios:2e624420271aced21a96bf',
    messagingSenderId: '1066839315758',
    projectId: 'reelstream1644',
    storageBucket: 'reelstream1644.firebasestorage.app',
    iosBundleId: 'com.example.reelStream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACgngk1fskzjnkwHomt7BwpVsaATeZvTQ',
    appId: '1:1066839315758:ios:2e624420271aced21a96bf',
    messagingSenderId: '1066839315758',
    projectId: 'reelstream1644',
    storageBucket: 'reelstream1644.firebasestorage.app',
    iosBundleId: 'com.example.reelStream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFE6A_ud9h_HYjWJHUoIGvd3UV1vRG7RE',
    appId: '1:1066839315758:web:5ca8171e0b3bbf9f1a96bf',
    messagingSenderId: '1066839315758',
    projectId: 'reelstream1644',
    authDomain: 'reelstream1644.firebaseapp.com',
    storageBucket: 'reelstream1644.firebasestorage.app',
  );
}
